package ru.cashprediction.core.ui.token;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Представления токенов для трёх инструментов: CSS-переменные web, looked-up colors JavaFX и значения
 * {@code UIManager} Swing (спецификация v2, §1.1–§1.2).
 *
 * <p>Ядро не зависит от {@code java.desktop}, поэтому {@link #swingDefaults()} отдаёт не {@code java.awt.Color},
 * а числа ARGB ({@link Integer}), {@link FontToken} и {@link Boolean}; клиент Swing сам оборачивает их в
 * {@code ColorUIResource}/{@code FontUIResource}. Все результаты детерминированы (порядок ключей фиксирован),
 * чтобы сгенерированный {@code /app/tokens.css} и стили FX не менялись от запуска к запуску.</p>
 *
 * <p>Класс без состояния, потокобезопасен.</p>
 */
public final class TokenCss {

    /** Ключи {@code UIManager} со шрифтом {@link FontToken#BASE} («все ключи *.font», §1.2). */
    private static final List<String> SWING_BASE_FONT_KEYS = List.of("Button.font", "ToggleButton.font", "Label.font",
            "Menu.font", "MenuItem.font", "CheckBoxMenuItem.font", "RadioButtonMenuItem.font", "MenuBar.font",
            "PopupMenu.font", "Table.font", "TableHeader.font", "TextField.font", "FormattedTextField.font",
            "TextArea.font", "ComboBox.font", "List.font", "CheckBox.font", "RadioButton.font", "Spinner.font",
            "OptionPane.messageFont", "OptionPane.buttonFont", "TitledBorder.font", "FileChooser.listFont",
            "TabbedPane.font", "EditorPane.font", "Panel.font", "ScrollPane.font", "Viewport.font", "ToolBar.font",
            "Slider.font", "ProgressBar.font", "Tree.font", "TextPane.font", "PasswordField.font");

    private TokenCss() {
    }

    /**
     * Таблица стилей web-клиента {@code /app/tokens.css}: переменные {@code :root} для цветов, шрифтов и размеров
     * плюс базовое правило {@code html, body}. Web не реагирует на {@code prefers-color-scheme} (одна светлая тема).
     *
     * @return CSS-текст с переводами строк LF
     */
    public static String webCss() {
        StringBuilder sb = new StringBuilder(4096);
        // Служебный комментарий CSS пользователь не видит; латиницей, чтобы в коде ядра не было русских литералов (L13).
        sb.append("/* Generated by CashPrediction core from design tokens (TokenCss.webCss); do not edit. */\n");
        sb.append(":root {\n");
        for (ColorToken token : ColorToken.values()) {
            variable(sb, token.cssVar(), token.css());
        }
        variable(sb, "--cp-font-family", DesignTokens.FONT_FAMILY);
        variable(sb, "--cp-mono-family", DesignTokens.MONO_FAMILY);
        for (FontToken font : FontToken.values()) {
            variable(sb, font.cssVar(), font.sizePx() + "px");
        }
        variable(sb, "--cp-spacing", px(DesignTokens.SPACING));
        variable(sb, "--cp-row-height", px(DesignTokens.ROW_HEIGHT));
        variable(sb, "--cp-header-height", px(DesignTokens.HEADER_HEIGHT));
        variable(sb, "--cp-control-height", px(DesignTokens.CONTROL_HEIGHT));
        variable(sb, "--cp-toolbar-height", px(DesignTokens.TOOLBAR_HEIGHT));
        variable(sb, "--cp-status-height", px(DesignTokens.STATUS_HEIGHT));
        variable(sb, "--cp-button-min-width", px(DesignTokens.BUTTON_MIN_WIDTH));
        variable(sb, "--cp-radius", px(DesignTokens.RADIUS));
        variable(sb, "--cp-card-min-width", px(DesignTokens.CARD_MIN_WIDTH));
        variable(sb, "--cp-filter-width", px(DesignTokens.FILTER_WIDTH));
        variable(sb, "--cp-tooltip-max-width", px(DesignTokens.TOOLTIP_MAX_WIDTH));
        variable(sb, "--cp-shadow-blur", px(DesignTokens.SHADOW_BLUR));
        variable(sb, "--cp-shadow-offset-y", px(DesignTokens.SHADOW_OFFSET_Y));
        for (DialogWidth width : DialogWidth.values()) {
            variable(sb, "--cp-dialog-" + width.name().toLowerCase(java.util.Locale.ROOT).replace('_', '-'), px(width.px()));
        }
        sb.append("}\n");
        sb.append("html, body {\n");
        sb.append("  margin: 0;\n");
        sb.append("  background: var(").append(ColorToken.BG_WINDOW.cssVar()).append(");\n");
        sb.append("  color: var(").append(ColorToken.TEXT_PRIMARY.cssVar()).append(");\n");
        sb.append("  font-family: var(--cp-font-family);\n");
        sb.append("  font-size: var(").append(FontToken.BASE.cssVar()).append(");\n");
        sb.append("}\n");
        return sb.toString();
    }

    /**
     * Looked-up colors для корневого стиля JavaFX: {@code -cp-bg-window: #F6F8FA} и т. д.
     *
     * @return неизменяемая упорядоченная карта «имя → CSS-цвет»
     */
    public static Map<String, String> fxLookups() {
        Map<String, String> result = new LinkedHashMap<>();
        for (ColorToken token : ColorToken.values()) {
            result.put(token.fxLookup(), token.css());
        }
        return Collections.unmodifiableMap(result);
    }

    /**
     * Значения {@code UIManager} для Metal с темой из токенов: цвета как {@link Integer} ARGB, шрифты как
     * {@link FontToken}, флаг {@code swing.boldMetal} как {@link Boolean#FALSE}.
     *
     * @return неизменяемая упорядоченная карта «ключ UIManager → значение»
     */
    public static Map<String, Object> swingDefaults() {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("swing.boldMetal", Boolean.FALSE);
        color(result, "Panel.background", ColorToken.BG_WINDOW);
        color(result, "ToolBar.background", ColorToken.BG_WINDOW);
        color(result, "MenuBar.background", ColorToken.BG_WINDOW);
        color(result, "Viewport.background", ColorToken.BG_SURFACE);
        color(result, "ScrollPane.background", ColorToken.BG_SURFACE);
        color(result, "OptionPane.background", ColorToken.BG_SURFACE);
        color(result, "TextField.background", ColorToken.BG_SURFACE);
        color(result, "TextArea.background", ColorToken.BG_SURFACE);
        color(result, "List.background", ColorToken.BG_SURFACE);
        color(result, "Table.background", ColorToken.BG_SURFACE);
        color(result, "Table.foreground", ColorToken.TEXT_PRIMARY);
        color(result, "Table.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "Table.selectionForeground", ColorToken.TEXT_PRIMARY);
        color(result, "Table.gridColor", ColorToken.BORDER);
        color(result, "TableHeader.background", ColorToken.BG_ALT);
        color(result, "TableHeader.foreground", ColorToken.TEXT_PRIMARY);
        color(result, "Label.foreground", ColorToken.TEXT_PRIMARY);
        color(result, "Menu.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "Menu.selectionForeground", ColorToken.TEXT_PRIMARY);
        color(result, "MenuItem.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "MenuItem.selectionForeground", ColorToken.TEXT_PRIMARY);
        color(result, "CheckBoxMenuItem.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "RadioButtonMenuItem.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "List.selectionBackground", ColorToken.ACCENT_WEAK);
        color(result, "List.selectionForeground", ColorToken.TEXT_PRIMARY);
        color(result, "Button.select", ColorToken.ACCENT_WEAK);
        color(result, "ToggleButton.select", ColorToken.ACCENT_WEAK);
        color(result, "Separator.foreground", ColorToken.BORDER);
        color(result, "ToolTip.background", ColorToken.TOOLTIP_BG);
        color(result, "ToolTip.foreground", ColorToken.TOOLTIP_TEXT);
        color(result, "Component.focusColor", ColorToken.ACCENT);
        for (String key : SWING_BASE_FONT_KEYS) {
            result.put(key, FontToken.BASE);
        }
        result.put("ToolTip.font", FontToken.LEGEND);
        return Collections.unmodifiableMap(result);
    }

    private static void variable(StringBuilder sb, String name, String value) {
        sb.append("  ").append(name).append(": ").append(value).append(";\n");
    }

    private static void color(Map<String, Object> map, String key, ColorToken token) {
        map.put(key, token.argb());
    }

    private static String px(int value) {
        return value + "px";
    }
}
